#!/usr/bin/env bash
# sonarqube-setup.sh — Quick SonarQube/SonarCloud setup for any project
# Usage: ./sonarqube-setup.sh [--local] [--cloud] [--ci]
#
# Modes:
#   --local   Start SonarQube via Docker + configure project (default)
#   --cloud   Configure SonarCloud (no local server)
#   --ci      Generate CI pipeline config (GitHub Actions / GitLab CI)
#
# Requirements:
#   - Docker (for --local mode)
#   - sonar-scanner CLI or project build tool (Maven/Gradle/npm)

set -euo pipefail

MODE="local"
PROJECT_KEY=""
PROJECT_NAME=""
SONAR_TOKEN=""
SONAR_ORG=""
SONAR_URL="http://localhost:9000"
CI_PLATFORM="github"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --local)     MODE="local"; shift ;;
    --cloud)     MODE="cloud"; shift ;;
    --ci)        MODE="ci"; shift ;;
    --key)       PROJECT_KEY="$2"; shift 2 ;;
    --name)      PROJECT_NAME="$2"; shift 2 ;;
    --token)     SONAR_TOKEN="$2"; shift 2 ;;
    --org)       SONAR_ORG="$2"; shift 2 ;;
    --url)       SONAR_URL="$2"; shift 2 ;;
    --gitlab)    CI_PLATFORM="gitlab"; shift ;;
    --github)    CI_PLATFORM="github"; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Auto-detect project info ──
detect_project() {
  # Try package.json
  if [[ -f "package.json" ]]; then
    PROJECT_KEY="${PROJECT_KEY:-$(grep -o '"name":\s*"[^"]*"' package.json | head -1 | sed 's/"name":\s*"//;s/"//' || echo "")}"
    PROJECT_NAME="${PROJECT_NAME:-$PROJECT_KEY}"
    echo "Detected: Node.js project"
    return
  fi

  # Try pom.xml
  if [[ -f "pom.xml" ]]; then
    PROJECT_KEY="${PROJECT_KEY:-$(grep -oP '(?<=<artifactId>)[^<]+' pom.xml | head -1 || echo "")}"
    PROJECT_NAME="${PROJECT_NAME:-$PROJECT_KEY}"
    echo "Detected: Maven project"
    return
  fi

  # Try build.gradle
  if [[ -f "build.gradle" ]] || [[ -f "build.gradle.kts" ]]; then
    PROJECT_KEY="${PROJECT_KEY:-$(basename "$(pwd)")}"
    PROJECT_NAME="${PROJECT_NAME:-$PROJECT_KEY}"
    echo "Detected: Gradle project"
    return
  fi

  # Try setup.py / pyproject.toml
  if [[ -f "pyproject.toml" ]] || [[ -f "setup.py" ]]; then
    PROJECT_KEY="${PROJECT_KEY:-$(basename "$(pwd)")}"
    PROJECT_NAME="${PROJECT_NAME:-$PROJECT_KEY}"
    echo "Detected: Python project"
    return
  fi

  # Fallback
  PROJECT_KEY="${PROJECT_KEY:-$(basename "$(pwd)")}"
  PROJECT_NAME="${PROJECT_NAME:-$PROJECT_KEY}"
  echo "No specific build system detected, using directory name"
}

detect_project

echo "=== SonarQube Setup ==="
echo "Mode:    ${MODE}"
echo "Project: ${PROJECT_NAME} (${PROJECT_KEY})"
echo ""

# ── Local Mode: Start SonarQube via Docker ──
if [[ "$MODE" == "local" ]]; then
  echo "--- Step 1/4: Start SonarQube Docker ---"

  if ! command -v docker &>/dev/null; then
    echo "ERROR: Docker is required for local mode"
    echo "Install Docker: https://docs.docker.com/get-docker/"
    exit 1
  fi

  # Check if already running
  if docker ps --filter "name=sonarqube" --format "{{.Names}}" | grep -q "sonarqube"; then
    echo "SonarQube already running"
  else
    echo "Starting SonarQube (Community Edition)..."
    docker run -d \
      --name sonarqube \
      -p 9000:9000 \
      -v sonarqube_data:/opt/sonarqube/data \
      -v sonarqube_logs:/opt/sonarqube/logs \
      -v sonarqube_extensions:/opt/sonarqube/extensions \
      sonarqube:community

    echo "Waiting for SonarQube to start..."
    RETRIES=30
    while [[ $RETRIES -gt 0 ]]; do
      if curl -sf "${SONAR_URL}/api/system/status" 2>/dev/null | grep -q "UP"; then
        echo "SonarQube is ready!"
        break
      fi
      RETRIES=$((RETRIES - 1))
      sleep 5
    done

    if [[ $RETRIES -eq 0 ]]; then
      echo "WARNING: SonarQube may not be ready yet. Check ${SONAR_URL}"
    fi
  fi
  echo ""

  echo "--- Step 2/4: Create sonar-project.properties ---"
  if [[ -f "sonar-project.properties" ]]; then
    echo "sonar-project.properties already exists, skipping"
  else
    cat > sonar-project.properties <<PROPS
# SonarQube Analysis Configuration
# Generated by sonarqube-setup.sh

sonar.projectKey=${PROJECT_KEY}
sonar.projectName=${PROJECT_NAME}

# Source configuration
sonar.sources=src
# sonar.tests=test,tests,__tests__

# Language-specific settings
# sonar.java.binaries=target/classes
# sonar.java.libraries=target/dependency/*.jar
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.python.coverage.reportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/node_modules/**,**/vendor/**,**/build/**,**/dist/**,**/*.test.*,**/*.spec.*
sonar.coverage.exclusions=**/*test*/**,**/*spec*/**,**/mocks/**

# Encoding
sonar.sourceEncoding=UTF-8

# Quality Gate
# sonar.qualitygate.wait=true
PROPS
    echo "Created sonar-project.properties"
  fi
  echo ""

  echo "--- Step 3/4: Detect analysis method ---"
  SCAN_CMD=""

  if [[ -f "pom.xml" ]]; then
    echo "Maven detected. Use:"
    SCAN_CMD="mvn clean verify sonar:sonar -Dsonar.host.url=${SONAR_URL}"
    echo "  ${SCAN_CMD}"
  elif [[ -f "build.gradle" ]] || [[ -f "build.gradle.kts" ]]; then
    echo "Gradle detected. Add to build.gradle:"
    echo '  plugins { id "org.sonarqube" version "5.0.0.4638" }'
    SCAN_CMD="./gradlew sonar -Dsonar.host.url=${SONAR_URL}"
    echo "  ${SCAN_CMD}"
  elif [[ -f "package.json" ]]; then
    echo "Node.js detected. Install sonar-scanner:"
    echo "  npm install -D sonarqube-scanner"
    SCAN_CMD="npx sonar-scanner -Dsonar.host.url=${SONAR_URL}"
    echo "  ${SCAN_CMD}"
  elif [[ -f "pyproject.toml" ]] || [[ -f "setup.py" ]]; then
    echo "Python detected. Install sonar-scanner:"
    echo "  pip install pysonar-scanner"
    SCAN_CMD="sonar-scanner -Dsonar.host.url=${SONAR_URL}"
    echo "  ${SCAN_CMD}"
  else
    echo "Generic project. Install sonar-scanner CLI:"
    echo "  brew install sonar-scanner  # macOS"
    echo "  # or download from https://docs.sonarqube.org/latest/analyzing-source-code/scanners/sonarscanner/"
    SCAN_CMD="sonar-scanner -Dsonar.host.url=${SONAR_URL}"
    echo "  ${SCAN_CMD}"
  fi
  echo ""

  echo "--- Step 4/4: Summary ---"
  echo "  SonarQube URL:  ${SONAR_URL}"
  echo "  Default login:  admin / admin (change on first login!)"
  echo "  Project key:    ${PROJECT_KEY}"
  echo "  Config file:    sonar-project.properties"
  echo ""
  echo "  Run analysis:   ${SCAN_CMD}"
  echo "  View results:   ${SONAR_URL}/dashboard?id=${PROJECT_KEY}"
  echo ""
  echo "  Stop server:    docker stop sonarqube"
  echo "  Remove server:  docker rm sonarqube && docker volume rm sonarqube_data sonarqube_logs sonarqube_extensions"
fi

# ── Cloud Mode: Configure SonarCloud ──
if [[ "$MODE" == "cloud" ]]; then
  SONAR_URL="https://sonarcloud.io"

  echo "--- SonarCloud Configuration ---"
  echo ""

  if [[ -z "$SONAR_ORG" ]]; then
    echo "Organization is required for SonarCloud."
    echo "Usage: ./sonarqube-setup.sh --cloud --org YOUR_ORG --key PROJECT_KEY --token YOUR_TOKEN"
    echo ""
    echo "Get your token at: https://sonarcloud.io/account/security"
    exit 1
  fi

  echo "Creating sonar-project.properties for SonarCloud..."
  cat > sonar-project.properties <<PROPS
# SonarCloud Analysis Configuration
# Generated by sonarqube-setup.sh

sonar.host.url=https://sonarcloud.io
sonar.organization=${SONAR_ORG}
sonar.projectKey=${PROJECT_KEY}
sonar.projectName=${PROJECT_NAME}

# Source configuration
sonar.sources=src
# sonar.tests=test,tests,__tests__

# Coverage reports
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.python.coverage.reportPaths=coverage.xml
# sonar.java.binaries=target/classes

# Exclusions
sonar.exclusions=**/node_modules/**,**/vendor/**,**/build/**,**/dist/**
sonar.coverage.exclusions=**/*test*/**,**/*spec*/**

# Quality Gate
sonar.qualitygate.wait=true
PROPS

  echo "Created sonar-project.properties"
  echo ""
  echo "  Dashboard: https://sonarcloud.io/project/overview?id=${PROJECT_KEY}"
  echo "  Run:       sonar-scanner -Dsonar.token=YOUR_TOKEN"
  echo ""

  if [[ -n "$SONAR_TOKEN" ]]; then
    echo "  Token provided. You can run analysis immediately."
  else
    echo "  Get token: https://sonarcloud.io/account/security"
    echo "  Store as:  SONAR_TOKEN env var or GitHub secret"
  fi
fi

# ── CI Mode: Generate pipeline config ──
if [[ "$MODE" == "ci" ]]; then
  echo "--- CI Pipeline Generation ---"
  echo ""

  if [[ "$CI_PLATFORM" == "github" ]]; then
    mkdir -p .github/workflows
    cat > .github/workflows/sonarqube.yml <<'WORKFLOW'
name: SonarQube Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate blame

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Uncomment for Node.js projects:
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - run: npm ci
      # - run: npm test -- --coverage

      # Uncomment for Maven projects:
      # - name: Build and Test
      #   run: mvn clean verify

      # Uncomment for Gradle projects:
      # - name: Build and Test
      #   run: ./gradlew test jacocoTestReport

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: SonarQube Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
WORKFLOW

    echo "Created .github/workflows/sonarqube.yml"
    echo ""
    echo "Required GitHub Secrets:"
    echo "  SONAR_TOKEN    - SonarQube/SonarCloud authentication token"
    echo "  SONAR_HOST_URL - SonarQube server URL (skip for SonarCloud)"
    echo ""
    echo "Set secrets at: https://github.com/YOUR_ORG/YOUR_REPO/settings/secrets/actions"

  elif [[ "$CI_PLATFORM" == "gitlab" ]]; then
    cat > .sonar-gitlab-ci.yml <<'GITLAB'
# SonarQube Analysis for GitLab CI
# Add this to your .gitlab-ci.yml or include it

sonarqube-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
      -Dsonar.projectKey=${CI_PROJECT_NAME}
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.token=${SONAR_TOKEN}
      -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - merge_requests
    - main
    - develop
GITLAB

    echo "Created .sonar-gitlab-ci.yml"
    echo ""
    echo "Required GitLab CI/CD Variables:"
    echo "  SONAR_TOKEN    - SonarQube authentication token"
    echo "  SONAR_HOST_URL - SonarQube server URL"
    echo ""
    echo "Set variables at: Settings > CI/CD > Variables"
  fi
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Review sonar-project.properties and uncomment relevant settings"
echo "  2. Run your first analysis"
echo "  3. Check the dashboard for results"
echo "  4. Configure quality gates for your team's standards"
echo ""
